base_image: "anyscale/ray-ml:pinned-nightly-py37"
env_vars: {"RAY_grpc_keepalive_time_ms": 1200000}
debian_packages: []

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip uninstall -y ray
  - pip3 install -U https://s3-us-west-2.amazonaws.com/ray-wheels/test_wheels/unpin_early/cd14f5bdcbbe2bc845053bc12c8c4f811c2ff149/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  - pip3 install -U ray[default]
  - echo {{env["DATESTAMP"]}}
